### ISSUE TITLE
缺少libgcc_s_dw2-1.dll无法启动

### ISSUE THREAD

**Issue by Sev73n** [LewisTian/Premiere-Subtitle#2]
安装完成后打开提示缺少libgcc_s_dw2-1.dll
我自己下载后放到了system32和syswow64 还有软件的根目录
都无法启动

**Comment by taseikyo** [comment]
这个问题有好些人遇到 我也不知道为什么_(:з」∠)_毕竟辣鸡windows！

**Comment by taseikyo** [comment]
@Sev73n 我刚把Qt bin目录下的libgcc_s_dw2-1.dll上传了，现在试试看能不能运行

**Comment by Sev73n** [comment]
好像还是不行……那个……你用Qt能直接编译一个mac用的吗
我是mac 可以帮你测试~

**Comment by taseikyo** [comment]
那个得用mac上的Qt编译吧？

**Comment by taseikyo** [comment]
你可以把整个项目下下来在自己的mac上编译

**Comment by Sev73n** [comment]
我试试ᕕ(ᐛ)ᕗ
